/**
 * #define 预处理器指令测试
 */

import { InnoScriptParser, InnoScriptGenerator } from "../src/index";

describe("#define 预处理器", () => {
  const sampleIssWithDefines = `
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; 软件名称
#define MyAppName "Self Report"
; 软件版本
#define MyAppVersion "1.0.0"
; 发布者信息
#define MyAppPublisher "信息科技有限公司"
; 主程序可执行文件名
#define MyAppExeName "Self Report.exe"
; 文件关联显示名称
#define MyAppAssocName MyAppName + " File"
; 文件关联扩展名
#define MyAppAssocExt ".myp"
; 注册表Key
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
; 快捷方式显示名称
#define MyAppShortcutName "自助接报"

[Setup]
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename=myapp-setup
ChangesAssociations=yes

[Files]
Source: "{src}\\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs

[Icons]
Name: "{group}\\{#MyAppShortcutName}"; Filename: "{app}\\{#MyAppExeName}"
Name: "{autodesktop}\\{#MyAppShortcutName}"; Filename: "{app}\\{#MyAppExeName}"

[Registry]
Root: HKCR; Subkey: "{#MyAppAssocExt}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocKey}"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKCR; Subkey: "{#MyAppAssocKey}\\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\\{#MyAppExeName},0"
Root: HKCR; Subkey: "{#MyAppAssocKey}\\shell\\open\\command"; ValueType: string; ValueName: ""; ValueData: "\\"{app}\\{#MyAppExeName}\\" \\"%1\\""
`;

  it("应该能够提取 #define 定义", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, true);

    expect(config.Defines).toBeDefined();
    // 解析器可能会去除引号，所以我们检查包含而不是精确匹配
    expect(config.Defines?.MyAppName).toContain("Self Report");
    expect(config.Defines?.MyAppVersion).toContain("1.0.0");
  });

  it("应该保留 {#...} 引用当 preserveDefineReferences=true", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, true);

    expect(config.Setup?.AppName).toBe("{#MyAppName}");
    expect(config.Setup?.AppVersion).toBe("{#MyAppVersion}");
    expect(config.Setup?.AppPublisher).toBe("{#MyAppPublisher}");
  });

  it("应该替换 {#...} 引用当 preserveDefineReferences=false", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, false);

    // 注意：简单字面量替换不会去除引号
    expect(config.Setup?.AppName).toContain("Self Report");
    expect(config.Setup?.AppVersion).toContain("1.0.0");
  });

  it("应该能够生成带有 #define 的脚本", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, true);
    const generator = new InnoScriptGenerator();
    const generatedScript = generator.generate(config);

    expect(generatedScript).toContain("#define MyAppName");
    expect(generatedScript).toContain("{#MyAppName}");
  });

  it("应该正确处理 Icons 中的 {#...} 引用", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, true);

    expect(config.Icons).toBeDefined();
    expect(config.Icons?.[0].Name).toContain("{#MyAppShortcutName}");
    expect(config.Icons?.[0].Filename).toContain("{#MyAppExeName}");
  });

  it("应该正确处理 Registry 中的 {#...} 引用", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, true);

    expect(config.Registry).toBeDefined();
    expect(config.Registry?.[0].Subkey).toContain("{#MyAppAssocExt}");
    expect(config.Registry?.[1].Subkey).toContain("{#MyAppAssocKey}");
  });
});
