/**
 * #define Preprocessor Tests
 */

import { InnoScriptParser, InnoScriptGenerator } from "../src/index";

describe("#define Preprocessor", () => {
  const sampleIssWithDefines = `
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; Application name
#define MyAppName "Self Report"
; Application version
#define MyAppVersion "1.0.0"
; Publisher
#define MyAppPublisher "Tech Company"
; Main executable name
#define MyAppExeName "Self Report.exe"
; File association display name
#define MyAppAssocName MyAppName + " File"
; File association extension
#define MyAppAssocExt ".myp"
; Registry key
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
; Shortcut display name
#define MyAppShortcutName "Self Report App"

[Setup]
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename=myapp-setup
OutputDir=output
ChangesAssociations=yes

[Files]
Source: "{src}\\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs

[Icons]
Name: "{group}\\{#MyAppShortcutName}"; Filename: "{app}\\{#MyAppExeName}"
Name: "{autodesktop}\\{#MyAppShortcutName}"; Filename: "{app}\\{#MyAppExeName}"

[Registry]
Root: HKCR; Subkey: "{#MyAppAssocExt}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocKey}"; Flags: uninsdeletevalue
Root: HKCR; Subkey: "{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKCR; Subkey: "{#MyAppAssocKey}\\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\\{#MyAppExeName},0"
Root: HKCR; Subkey: "{#MyAppAssocKey}\\shell\\open\\command"; ValueType: string; ValueName: ""; ValueData: "\\"{app}\\{#MyAppExeName}\\" \\"%1\\""
`;

  it("should extract #define definitions", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, { preserveDefineReferences: true });

    expect(config.Defines).toBeDefined();
    expect(config.Defines?.MyAppName).toContain("Self Report");
    expect(config.Defines?.MyAppVersion).toContain("1.0.0");
  });

  it("should preserve {#...} references when preserveDefineReferences=true", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, { preserveDefineReferences: true });

    expect(config.Setup.AppName).toBe("{#MyAppName}");
    expect(config.Setup.AppVersion).toBe("{#MyAppVersion}");
    expect(config.Setup.AppPublisher).toBe("{#MyAppPublisher}");
  });

  it("should replace {#...} references when preserveDefineReferences=false", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, { preserveDefineReferences: false });

    expect(config.Setup.AppName).toContain("Self Report");
    expect(config.Setup.AppVersion).toContain("1.0.0");
  });

  it("should generate script with #define directives", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, { preserveDefineReferences: true });
    const generator = new InnoScriptGenerator();
    const generatedScript = generator.generate(config);

    expect(generatedScript).toContain("#define MyAppName");
    expect(generatedScript).toContain("{#MyAppName}");
  });

  it("should handle {#...} references in Icons section", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, { preserveDefineReferences: true });

    expect(config.Icons).toBeDefined();
    expect(config.Icons?.[0]?.Name).toContain("{#MyAppShortcutName}");
    expect(config.Icons?.[0]?.Filename).toContain("{#MyAppExeName}");
  });

  it("should handle {#...} references in Registry section", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, { preserveDefineReferences: true });

    expect(config.Registry).toBeDefined();
    expect(config.Registry?.[0]?.Subkey).toContain("{#MyAppAssocExt}");
    expect(config.Registry?.[1]?.Subkey).toContain("{#MyAppAssocKey}");
  });

  it("should handle string concatenation in defines", () => {
    const config = InnoScriptParser.parse(sampleIssWithDefines, { preserveDefineReferences: false });

    // MyAppAssocName = MyAppName + " File" = "Self Report File"
    expect(config.Defines?.MyAppAssocName).toContain("Self Report");
    expect(config.Defines?.MyAppAssocName).toContain("File");
  });
});